### ISSUE TITLE
What commits are safe to use?

### ISSUE THREAD

**Issue by simonjohansson** [dgryski/carbonapi#108]
The repo does not contain any tags or releases. :)

**Comment by dgryski** [comment]
This is a critical component of the monitoring stack at Booking.com.  We deploy builds from master.

This repository is kept green.  There is a CI at https://drone.io/github.com/dgryski/carbonapi that tests every push.  I code review all commits from other people.  If a feature is going to take more time than a single commit, work is done on a branch before being merged in (as with the cairo support).
