### ISSUE TITLE
Implement correct monthly data summarization

### ISSUE THREAD

**Issue by Ishitori** [dgryski/carbonapi#121]
Currently, when you write something like summarize(metric, "1month", "sum") data is summarized based on 30 days interval, ignoring the fact that there might be 28/29/30/31 days in a month.

Would be great to fix this.

**Comment by dgryski** [comment]
We can change the summary p eriod to be "1calmon" (calendar month) or something.  Graphite has hard-coded "1 month == 30 days".   We don't want to break that, but we can extend it.

**Comment by JaderDias** [comment]
In my opinion it's impossible to fix this problem since the graphite format=raw requires a regular step.

**Comment by nnuss** [comment]
Is format=raw the only one incapable of this?

**Comment by JaderDias** [comment]
@nnuss not only format=raw, but also the internal representation o a time series. In order to implement this feature we would have to create a different expression evaluation engine specifically for it.
