### ISSUE TITLE
Write access logs in the same format used by nginx

### ISSUE THREAD

**Issue by JaderDias** [dgryski/carbonapi#126]
Nginx access logs have lots of useful information, namely:
- referer
- HTTP method
- source IP
- BasicAuth user
- HTTP Status Code

If carbonapi produced logs in the same format and with the same information we could reuse every system that understands Nginx access logs and be able to monitor and query carbonapi logs in the same way

**Comment by dgryski** [comment]
I'm hesitant to move logging *back* to syslog instead of stdout.  Could you update your package to allow sending formatted logs to stdout also?

**Comment by JaderDias** [comment]
It seems that syslog can become a bottleneck more often than stdout or even a file on the disk, I agree with you that we shouldn't write directly to syslog.

**Comment by JaderDias** [comment]
Commit https://github.com/dgryski/carbonapi/commit/9e207ccc3f5ba4eb0715eb4963a76c1cd831ec34 prints the access logs in the combined log format to STDOUT.

In order to print them to the correct destination we need to accept the following pull request: https://github.com/dgryski/carbonzipper/pull/19

**Comment by dgryski** [comment]
Closed with 305fc5075c3221f135c1897101378111d129f4df
