### ISSUE TITLE
Return globbed metrics in consistent order

### ISSUE THREAD

**Issue by arodland** [dgryski/carbonapi#128]
when dealing with brace expansion, graphite-api and graphite-web return multiple metrics in a consistent order, while carbonapi returns them in the order it gets them from carbonzipper, which is inconsistent, even between subsequent queries for the same thing.

The rules graphite-web and graphite-api apply are:

* when a segment contains a `{this,that}` brace expansion list, it returns metrics with `this` before metrics with `that`. It proceeds hierarchically by level, so `{a,b}.{c,d}` returns `a.c`, `a.d`, `b.c`, then `b.d` assuming they all exist.
* otherwise, when a segment contains a `*`, `?`, or `[a-z]` glob, it returns metrics sorted by that segment.

If you never use brace expansion, the second rule is basically the same as using `sortByName` all over the place, but the brace expansion rule provides a (nice, useful) level of control that isn't available anywhere else in the API.

Ideally, I would like to be fully consistent with graphite-api, so that I have that level of control and so that my graphs are identical from one API to the next. Less ideally, I would like *any* consistent return value that doesn't change from query to query unless the actual present metrics changed — "always `sortByName` if any kind of glob is present" is a rule that would satisfy this.

I'm familiar with Go and I'd be happy to do the work myself, but I need some direction on approach before I go diving into a PR :)

**Comment by nnuss** [comment]
I think this is sufficiently fixed by #129 @arodland; unless you want to keep this open for multi-brace-per-segment? Eg.
```
target=a.{c,d}{y,x}.e:
a.cy.e
a.cx.e
a.dy.e
a.dx.e
```

**Comment by arodland** [comment]
@nnuss I'm happy to close it. Thank you.
