### ISSUE TITLE
switch away from md5 for caching

### ISSUE THREAD

**Issue by dgryski** [dgryski/carbonapi#139]
Something faster and/or more secure

**Comment by nnuss** [comment]
Do you think SipHash is sufficient ? (also I'm less versed in what the "short input" limits there are)
-or-
Given we hash a the form (URI param) data with only the barest of sanitization should we go with something more collision resistant ? (SHA2 family or Whirlpool maybe)

**Comment by dgryski** [comment]
I want something with collision resistance. So, SHA and friends or BLAKE2. SipHash is not appropriate here.
