### ISSUE TITLE
movingAverage/movingMedian should fetch data from before the time interval

### ISSUE THREAD

**Issue by arodland** [dgryski/carbonapi#151]
(graphite-api calls this "bootstrapping"). i.e. if I'm doing `movingAverage(x, "1h")` with a time range of -12h to now, it should fetch data back to -13h so that it can actually *output* points starting at -12h.

It looks like expr.Metrics() can support this, but the parsing for movingAverage/movingMedian is a little more complicated than the functions that are handled in there now.

**Comment by dgryski** [comment]
We've discussed this in the past. The problem is that we don't know the aggregation for a time series so we don't know how far back we need query in order to get the right number of points. And if we do query more points we might change to another aggregation level meaning we'd need even more points.

**Comment by arodland** [comment]
For the "number of points" variant I can see how that would be a problem, but for the "interval" variant shouldn't it be possible just to use that interval? I guess the inconsistent behavior would be a bit annoying, but it would work better at least in one case.

**Comment by dgryski** [comment]
True. I'm not sure about the interval variant -- do we implement it? I'm open to any solution that is correct and doesn't require multiple fetches.

**Comment by arodland** [comment]
Yes, carbonapi already supports the interval variant — it's the etString branch of the switch on the argument type. I try to avoid the number-of-points variant because it means that the averaging time changes with the aggregation, and I hardly ever want that.

**Comment by dgryski** [comment]
Should be easy to add, then.  In `expr.Metrics()`, add a case to handle `movingAverage` and `movingMedian` that adjusts the start time, and then adjust it back when constructing the response.

**Comment by dgryski** [comment]
@arodland Were you going to work on this?

**Comment by arodland** [comment]
@dgryski yeah, I have some working code, I'm just not entirely happy with the state of it. Pushed it up as https://github.com/arodland/carbonapi/tree/moving-average for you to do with as you like.
