### ISSUE TITLE
Add support for "midnight", "noon", "teatime" for dateParamToEpoch function

### ISSUE THREAD

**Issue by liangjacky** [dgryski/carbonapi#157]
if no date given in the string, assume today. Otherwise parse the date.

**Comment by nnuss** [comment]
I'm :thumbsdown: on "teatime"

**Comment by dgryski** [comment]
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/attime.py#L65

**Comment by nnuss** [comment]
Yes and if my read is correct "tea[timeywimey](https://youtu.be/mDsN5lWLKU0?t=1m13s)" also passes - that doesn't mean it's a terribly good idea for us to support it. Also it was added at the big-bang of the project and not as a feature request later on.

"midnight" and "noon" I can maybe get behind given the confusion a number whom are used to 12-hour time have with 12am / 12pm.

If we're determined to add "teatime" can we also include:
- `breakfast`
- `2ndbreakfast` -also- `secondbreakfast`
- `elevenses` -possibly- `brunch`
- `lunch` -also- `luncheon`
- `naptime` -possibly- `siesta`
- `dinner`
- `teatime` -possibly- `tea` -also- `afternoontea`
- `supper`
- `bedtime`
(allowing for an optional "time" suffix. Eg. lunchtime)

**Comment by dgryski** [comment]
`teatime` has precedence in the Unix ecosystem -- the `at` command for example.

**Comment by nnuss** [comment]
Ah, true and `at` compatible times were a motivation there.
See also:
[graphite-web #1691: Graphite at(1) support](/graphite-project/graphite-web/issues/1691)
[graphite-web #263: Some from and until time references in render API do not work as documented, some future times work and some do not](/graphite-project/graphite-web/issues/263)

**Comment by nnuss** [comment]
And they do have a test for it. Ok :tea: time.

**Comment by liangjacky** [comment]
https://github.com/dgryski/carbonapi/pull/158
