### ISSUE TITLE
Listen IP

### ISSUE THREAD

**Issue by rlex** [dgryski/carbonapi#176]
Hello, is it possible to have something like

```
carbonapi -z=http://127.0.0.1:8080 -p 127.0.0.1:8081
```

So user can choose on which IP carbonapi listens?

**Comment by dgryski** [comment]
Yes, that's an easy fix.  The slightly tricky part is not breaking backwards compatibility with existing init scripts.  Maybe add an `-addr` option which defaults to `"0.0.0.0"`.  Your example would become:
```
carbonapi -z=http://127.0.0.1:8080 -addr=0.0.0.0 -p 8081"
```

We could also check for `:` in the port string, and add one if there's none there.  Need to think how that will play with ipv6 addresses.

**Comment by rlex** [comment]
maybe add something like --address-family={ipv4,ipv6,all} as well.
Right now by default it listens at 

```
root@***:~# netstat -tulpn | grep carbonapi
tcp6       0      0 :::8082                 :::*                    LISTEN      13094/carbonapi
```

Which responds to both v4 and v6

**Comment by Civil** [comment]
If it won't be fixed/merged in a day or two, I might just move that to a config file (there is a bunch of changes I'm working on that will introduce a config file and some logging changes, same as carbonzipper now have in master).

**Comment by deniszh** [comment]
It's already merged in https://github.com/dgryski/carbonapi/pull/194, no?

**Comment by dgryski** [comment]
This has been merged.  Please file has a new bug if there are issues with the implementation.
