### ISSUE TITLE
Queries with multiple globs differ in behavior between Graphite-Web and carbonapi

### ISSUE THREAD

**Issue by birryree** [dgryski/carbonapi#185]
I just created a new Graphite stack atop `go-carbon`, `carbonserver`, `carbonapi`, and `carbonzipper`, migrating data from a still-running legacy system that uses the standard Python-based Graphite/Carbon and graphite-web setup.

In Grafana, I have a dashboard that uses multiple templated variables, as shown below:

![image](https://cloud.githubusercontent.com/assets/809026/22945865/b2a443c6-f2c3-11e6-9626-75aefdcc6bd0.png)

When this dashboard fires off queries with multiple values for multiple globs, I'm seeing different behavior between `carbonapi` and `graphite-web`.

Here's the `render` query generated by Grafana:

```
groupByNode(misc.prod.{us-east-1,eu-west-1,ap-northeast-1}.{service1,service2,service3,service4,unknown}.requests.{subservice1,subservice2,subservice3,subservice4,subservice5,subservice6,subservice7,subservice8,subservice9,subservice10}.total.count, 5, 'sum')`
```

When testing this out against `carbonapi` with `curl` using the parameters that Grafana also uses:

 
```
curl "localhost:8080/render/?target=groupByNode(misc.prod.%7Bus-east-1%2Ceu-west-1%2Cap-northeast-1 \
%7D.%7Bservice1%2Cservice2%2Cservice3%2Cservice4%2Cunknown%7D.requests. \
%7Bsubservice1%2Csubservice2%2Csubservice3%2Csubservice4%2Csubservice5%2Csubservice6 \
%2Csubservice7%2Csubservice8%2Csubservice9%2Csubservice10%7D.total.count%2C%205%2C% \
20'sum')&from=-1h&until=now&format=json&maxDataPoints=1345"
```

A list of nulls is returned, and strangely for **only two of the subservices listed**

```[{"target":"subservice1","datapoints":[[null,1487098390],[null,1487098400],[null,1487098410],[null,1487098420],[null,1487098430]...[null,1487101970],[null,1487101980]]},{"target":"subservice2","datapoints":[[null,1487098390],[null,1487098400],[null,1487098410],[null,1487098420],[null,1487098430],[null,1487098440],[null,1487098450],[null,1487098460],[null,1487098470],...[null,1487101980]]}]```

Against the graphite-web instance, the same query generates the following data, and returns all subservice data, including a bunch of null values.

```
[{"target": "subservice1", "datapoints": [[54.0, 1487099150], [93.0, 1487099160], [109.0, 1487099170], [83.0, 1487099180], [47.0, 1487099190], [46.0, 1487099200], [70.0, 1487099210], [38.0, 1487099220], [54.0, 1487099230], [34.0, 1487099240], [39.0, 1487099250], [121.0, 1487099260], [58.0, 1487099270], [51.0, 1487099280], [56.0, 1487099290], [28.0, 1487099300], [8.0, 1487099310], [92.0, 1487099320], [70.0, 1487099330], [91.0, 1487099340], [64.0, 1487099350], [113.0, 1487099360], [87.0, 1487099370], [39.0, 1487099380], [60.0, 1487099390], [93.0, 1487099400], ..., [4.0, 1487102730], [null, 1487102740]]},
{"target": "subservice2", "datapoints": [[null, 1487099150], [null, 1487099160], [null, 1487099170], [null, 1487099180], [null, 1487099190], ...
{"target": "subservice2", "datapoints": [[null, 1487099350], [2.0, 1487099360], [null, 1487099370], [null, 1487099380], [null, 1487099390], [null, 1487099400], [null, 1487099410], [1.0, 1487099420], [5.0, 1487099430], [null, 1487099440], [null, 1487099450], [null, 1487099460], [null, 1487099470], [null, 1487099480], [null, 1487099490], [null, 1487099500], [null, 1487099510], [1.0, 1487099520], [1.0, 1487099530], ...
```

Some additional information about the data:

* Not every combination of `$Env`, `$Region`, `$Tenant`, and `$Service` exists, so there are some series queries that would not generate any data.

I could potentially help with investigating/patching this behavior into `carbonapi` to make it more consistent with Graphite-Web, but I wanted to just bring this up right now to see if it's a known issue or something up with the query being generated.

**Comment by dgryski** [comment]
At a quick glance, this *might* have to do with the `Max Globs` setting for `carbonserver`: https://github.com/grobian/carbonserver/blob/master/main.go#L57

**Comment by birryree** [comment]
@dgryski I changed my `carbonserver` to use a much higher `maxexpand` value and it resolved the discrepancies I saw between my instances. Thanks for the quick insight!
