### ISSUE TITLE
No CORS headers in response to OPTIONS (breaks preflighted AJAX requests)

### ISSUE THREAD

**Issue by zaptm** [dgryski/carbonapi#40]
The response to an OPTIONS request doesn't include the CORS headers that an preflight AJAX request expects[1] which makes the browser to refuse to perform the request.

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

**Comment by JaderDias** [comment]
Maybe it has to answer like this
 
Status Code:307 Internal Redirect
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://jdias-off.dev.booking.com
Location:<original request URL>
Non-Authoritative-Reason:HSTS

**Comment by JaderDias** [comment]
maybe if we ran carbonapi on top of nginx it would prevent us from having to implement this in this project

**Comment by grobian** [comment]
Can HAProxy do it? That one already is in front of it.

**Comment by grobian** [comment]
something like this should do it?
http://johntdyer.com/haproxy/2015/03/05/dynamic-access-control-allow-origin-header-in-haproxy.html
