### ISSUE TITLE
/info?target= not working

### ISSUE THREAD

**Issue by avereha** [dgryski/carbonapi#46]
If I send a request like this for a valid metric:
/info?target=metric_name
I always get the response:
empty target

If I sent the request like this:
/info/?target=metric_name
It's working.

**Comment by dgryski** [comment]
This has to do with the URL that's forwarded to carbonserver.

**Comment by dgryski** [comment]
carbonserver registers only `/info/` but carbonapi forwards both `/info/` and `/info`.

Not sure which the correct fix is.  For now, just use `/info/`.

 https://github.com/grobian/carbonserver/blob/0a670f203b3b8ec389e72f7721244cc34c887f50/main.go#L612
