### ISSUE TITLE
"summarize" last element mismatch

### ISSUE THREAD

**Issue by iftekhar25** [dgryski/carbonapi#57]
When aggregating in a fixed time range with from/until, e.g., xxxxxx0 to xxxxxx84, aggregate by 5 seconds, there is sometimes an extra or a missing value, the array length is variable by 1.

**Comment by nnuss** [comment]
Seems that graphite [0.9.12] will add a final null point beyond the requested range if it is not perfectly divisible in some cases.

## Graphite 0.9.12
http://graphite.example.com/render/?target=summarize(secondly.metric,"5s","min")&from=1490703150&until=1490703184&format=json
```json
[{"target":"summarize(secondly.metric, '5s', 'min')","datapoints":[[4600,1490703150],[4312,1490703155],[4514,1490703160],[4269,1490703165],[4321,1490703170],[4473,1490703175],[4240,1490703180],[null,1490703185]]}]
```

## Carbonapi
http://carbonapi.example.com/render/?target=summarize(secondly.metric,"5s","min")&from=1490703150&until=1490703184&format=json
```json
[{"target":"summarize(secondly.metric,'5s','min')","datapoints":[[4600,1490703150],[4312,1490703155],[4514,1490703160],[4269,1490703165],[4321,1490703170],[4473,1490703175],[4240,1490703180]]}]
```
