### ISSUE TITLE
Missing holtWinters* functions

### ISSUE THREAD

**Issue by JaderDias** [dgryski/carbonapi#66]
There are people that would like to use with carbonapi the holtWinters functions present in the python version

**Comment by dgryski** [comment]
Use https://github.com/datastream/holtwinters as a base instead of doing the math ourselves,  if possible.

**Comment by dgryski** [comment]
This has stalled slightly because it's not just a case of dropping-in a library.  HoltWinters needs several weeks of earlier data in order to correctly compute the seasonality for its predictions, which means we need to collect bootstrap data similar to how timeShift() works.

**Comment by dgryski** [comment]
I'm replacing the Holt-Winters code and hopefully will fix this at the same time.

**Comment by dgryski** [comment]
The patch in https://github.com/dgryski/carbonapi/commit/d4efd704fa36b876b4318dbba30b32af81068090 can be easily extended to add in the two other HW functions we're missing.

As far as I can tell, nobody is using them at the moment, so I won't implement that right now.

**Comment by dgryski** [comment]
This is sufficiently done.
