### ISSUE TITLE
Switch to https://github.com/gonum/plot

### ISSUE THREAD

**Issue by dgryski** [dgryski/carbonapi#67]
In addition to code.google.com shutting down, plotinum has moved to being part of the gonum project.  

This move also comes with a substantial number of breaking API changes.

**Comment by dgryski** [comment]
@JaderDias What's the status of your branch?  @Civil is planning on trying a port to Cairbo + cgo bindings.

**Comment by JaderDias** [comment]
This branch works except for missing labels in one of the axis

**Comment by dgryski** [comment]
Since plotinum is now broken, carbonapi no longer builds from source.  png support was experimental anyway, so I don't think anybody will complain.  I'll merge your branch and see if I can fix the missing axis issue.

**Comment by dgryski** [comment]
This is done.
