### ISSUE TITLE
Handle the HTTP request method OPTIONS properly to allow all kinds of cross-domain requests

### ISSUE THREAD

**Issue by JaderDias** [dgryski/carbonapi#68]
Sometimes the browser issues a HTTP request of the type OPTIONS when it's cross domain. I know a page that broke when using carbonapi because of this. It worked normally with the python version.

**Comment by dgryski** [comment]
Odd. I thought I had fixed this already.

**Comment by JaderDias** [comment]
I see https://github.com/dgryski/carbonapi/issues/40, but I can try to capture an example where it breaks and send to you. tcpdump, maybe?

**Comment by dgryski** [comment]
Closing.  Please re-open with a detailed failing test case.
