### ISSUE TITLE
missing, or incomplete support for stacked()

### ISSUE THREAD

**Issue by biappi** [dgryski/carbonapi#74]
example request: https://graphite-api.[redacted]/render?target=aliasByNode(stacked(sys.*[redacted]*.[redacted].connections)%2C%201)&from=1439439654&until=1439482974&format=json&maxDataPoints=640

**Comment by biappi** [comment]
i spoke IRL with @nnuss, and we were both confused by the fact an implemented function did return an empty list, while it should have errored with a 500.

```
$ curl -D- "https://graphite-api.[redacted]/render?target=stacked(aliasByNode(sys.*[redacted]*[redacted]*.[redacted]%2C%201))&from=-24h&until=now&format=json&maxDataPoints=427"
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Wed, 19 Aug 2015 14:02:44 GMT
Content-Length: 2
LBNODE: [redacted]

[]
```

**Comment by nnuss** [comment]
I took a look at this a while ago and a lack of a request context makes implementing this feature-compatible challenging.

Example:
    (assuming metrics are constant)
    /render?target=stacked(metric1, 'inbound')&target=stacked(metric2, 'inbound')&target=stacked(metric3)

Should result in a graph like:

    ____ metric2 ____________
    --- metric1 & metric3 ---

Maintaining that [potentially named] stack context between targets is the main issue to solve.

**Comment by dgryski** [comment]
@nnuss it's also possible this is the push we need to route a net/context through everything.

**Comment by dgryski** [comment]
Stacked support is now done.
