### ISSUE TITLE
Implement Kolmogorov–Smirnov 2 sample test

### ISSUE THREAD

**Issue by nnuss** [dgryski/carbonapi#76]
( Wikipedia description: [Kolmogorov–Smirnov Test](https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test) )

This would allow us to test, for example, a metric against itself in the past to see if the distribution has changed. Or if two metrics have similar distributions.

Naming might be among the hardest to implement.
My votes are:
* kolmogorovSmirnovTest2( seriesList, seriesList )
* ksTest2 (as the commonly used alias)

(I dislike the camelCasing standard here - but it maintains consistency)

"2" here because the 1-sample version, which essentially compares against a reference (usually normal) distribution, could also be implemented .. but there seem to be better tests for that.

**Comment by dgryski** [comment]
https://github.com/dgryski/go-onlinestats/blob/master/kstest.go
