### ISSUE TITLE
Support for Pearson Product Moment Correlation Coefficient (PPMCC)

### ISSUE THREAD

**Issue by nnuss** [dgryski/carbonapi#77]
As mentioned in [FB Gorilla paper](http://www.vldb.org/pvldb/vol8/p1816-teller.pdf) add support for sorting/filtering metrics against a test metric using PPMCC

**Comment by dgryski** [comment]
https://github.com/dgryski/go-onlinestats/blob/master/pearson.go

**Comment by dgryski** [comment]
https://github.com/dgryski/go-onlinestats/blob/master/spearman.go

**Comment by dgryski** [comment]
This is done.
