### ISSUE TITLE
Add Tukey outlier detection

### ISSUE THREAD

**Issue by dgryski** [dgryski/carbonapi#80]
https://github.com/dgryski/go-onlinestats/blob/master/tukey.go

**Comment by dgryski** [comment]
tukeyAbove() is done as part of https://github.com/dgryski/carbonapi/commit/4c2452b7aa463b17be398d9d0074f35f38a0c5b8

tukeyBelow() would probably still be ncie.

**Comment by nnuss** [comment]
Migrated tukeyBelow() to a new issue #100 to close this general one.
