### ISSUE TITLE
tukeyAbove(seriesList, interval, basis, n) : interval is unused

### ISSUE THREAD

**Issue by nnuss** [dgryski/carbonapi#99]
[This issue serves as a reminder / todo of interval's inteneded use.]

`interval` was conceived as a mechanism where the quantile threshold can be computed on a (leading IIRC) subset to enable this funciton to more efficiently process large seriesList over large intervals.

@dgryski and I discussed that we could move it to the end as an optional parameter.

**Comment by dgryski** [comment]
Done as https://github.com/dgryski/carbonapi/issues/103
